### ISSUE TITLE
choking on... things

### ISSUE THREAD

**Issue by dryack** [dryack/rt#5]
task ```rt AWS tagging (and all tagging frankly): can we move to something coherent like  product|service|version|owner|cost-center? | id:                           32a1077ae6e4f0591523d8186cbcddd6240fdef9417e9927eb0e8125878c7c72```

is added correctly, but running `rt` afterwards chokes with:

```Traceback (most recent call last):
        5: from /Users/dryack/bin/rt:319:in `<main>'
        4: from /Users/dryack/bin/rt:202:in `print_list'
        3: from /Users/dryack/bin/rt:68:in `prefixes'
        2: from /Users/dryack/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/abbrev.rb:81:in `abbrev'
        1: from /Users/dryack/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/abbrev.rb:81:in `each'
/Users/dryack/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/abbrev.rb:82:in `block in abbrev': undefined method `empty?' for nil:NilClass (NoMethodError)```

**Comment by dryack** [comment]
choking on the pipes...
